name: Deploy to ECS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image
        run: |
          docker build -t ${{ secrets.ECR_REPO }} ./app
          docker tag ${{ secrets.ECR_REPO }}:latest ${{ secrets.ECR_REPO }}:main
          docker push ${{ secrets.ECR_REPO }}:main

      - name: Deploy with Terraform
        working-directory: ./terraform
        run: |
          terraform init
          terraform plan -out tfplan
          terraform apply -auto-approve tfplan
