name: Deploy to ECS

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        env:
            AWS_REGION: us-west-2

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Log in to Amazon ECR
              run: |
                  aws ecr get-login-password --region ${{secrets.AWS_REGION}} \
                  | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}

            - name: Build, tag, and push Docker image
              run: |
                  docker build -t ${{ secrets.ECR_REPO }} ./app
                  docker push ${{ secrets.ECR_REPO }}

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Init
              working-directory: ./terraform
              run: terraform init

            - name: Terraform Apply
              working-directory: ./terraform
              run: terraform apply -auto-approve
    destroy:
        name: Terraform Destroy
        runs-on: ubuntu-latest
        if: github.event_name == 'workflow_dispatch'

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: 1.6.6

            - name: Terraform Init
              run: terraform init

            - name: Terraform Destroy
              run: terraform destroy -auto-approve
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
